name: Mirror gh-pages to the naked domain

on:
  workflow_run:
    workflows: ["CI/CD"] # after other workflow
    types:
      - completed

  # manual trigger
  workflow_dispatch:

jobs:
  sync:
    # only if CI/CD finished OK or is a manual trigger
    if: >
      github.event_name == 'workflow_dispatch' ||
      github.event.workflow_run.conclusion == 'success'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout origin gh-pages
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository }} # repo de origen
          ref: gh-pages
          fetch-depth: 0
      - name: Test repo access
        run: git ls-remote https://x-access-token:${{ secrets.NAKED_DOMAIN_TOKEN }}@github.com/commit-conf/naked-domain.git
      - name: Configure git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Push to target naked domain
        run: |
          git remote add target https://x-access-token:${{ secrets.NAKED_DOMAIN_TOKEN }}@github.com/commit-conf/naked-domain.git
          git push target HEAD:gh-pages --force
